### ISSUE TITLE
GLPI 10.02 Cron Jobs not working

### ISSUE THREAD

**Issue by schaelrippe** [Gianni-Rgg/GLPI-Maker#1]
Hi Gianni!
Thank you for your work here!!
We installed GLPI with your GLPI maker Today. We used ist with GLPI 10.02. It also installed PHP 8.1

Are this Versions supprtet? We see some errors with Cron Jobs. Jobs wich are sceduled are not beeing executed automatically but working if startet manualy.

Thank you for Feedback.
Greeting

**Comment by Gianni-Rgg** [comment]
Hi schaelrippe !

Thanks a lot for your message! I really appreciate that!

What was the error you seen with cron ?

Please, be sure to configure the Jobs in GLPI with CLI and not GLPI :

https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/crontasks.html?highlight=cli#configure-cli-mode

https://rdr-it.com/en/glpi-automatic-actions-configuration/

**Comment by schaelrippe** [comment]
Thanks for the interesting links. we have thus found the way to our problem. Thank you for that.

Here is how we fixed our issue:

**GLPI Webinterface**
Automatic jobs
mark all
Refresh
Execution mode->CLI

**Log in to CLI:**

Change to root user:
su -
Enter password

In root user:
Run command once and see if the jobs are running in GLPI if yes see next step:
sudo /usr/bin/php8.1 /var/www/html/glpi/front/cron.php &>/dev/null

Open crontab in editor:
crontab -e

Insert only this line (command above without SUDO and with "*/1 * * *" first asterisk stands for minutes hr days weeks months)
*/1 * * * /usr/bin/php8.1 /var/www/html/glpi/front/cron.php &>/dev/null

restart service cron to make the change effective
service cron restart

Thank you again for your great Work and help!

**Comment by Gianni-Rgg** [comment]
Thank you for your message!

GLPI-Maker is already supposed to add the cron task with the root user.

Can you confirm that you are using Debian?
Does the "php -v" command work? it may be the link with the "php" command that is causing the problem.

Can you confirm that the cron job:
\* \* \* \* \* php /var/www/html/glpi/front/cron.php &>/dev/null

Was listed in root's cron jobs after running the script?

It was a pleasure to help you.

**Comment by Gianni-Rgg** [comment]
No answer, I close the issue.
